# Generated by Django 4.0.8 on 2024-11-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_course_code_alter_course_credit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadvideo',
            name='video',
        ),
        migrations.AddField(
            model_name='uploadvideo',
            name='vimeo_url',
            field=models.URLField(blank=True, help_text='Ingresa la URL del video de Vimeo', max_length=500, null=True),
        ),
    ]
