# Generated by Django 4.0.8 on 2024-11-12 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_remove_uploadvideo_video_uploadvideo_vimeo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadvideo',
            name='video',
            field=models.FileField(blank=True, help_text='Valid video formats: mp4, mkv, wmv, 3gp, f4v, avi, mp3', null=True, upload_to='course_videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mkv', 'wmv', '3gp', 'f4v', 'avi', 'mp3'])]),
        ),
    ]
