# Generated by Django 4.2 on 2025-01-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0007_course_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="last_cert_code",
            field=models.IntegerField(default=0),
        ),
    ]
