# Generated by Django 4.2 on 2025-12-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0008_course_last_cert_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="code",
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="level",
            field=models.CharField(
                choices=[("Bachelor", "Bachelor Degree"), ("Master", "Master Degree")],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="semester",
            field=models.CharField(
                choices=[("First", "First"), ("Second", "Second"), ("Third", "Third")],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="slug",
            field=models.SlugField(blank=True, max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="summary",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="summary_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="summary_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="summary_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="summary_ru",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="course",
            name="title_en",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="title_es",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="title_fr",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="title_ru",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
