# Generated by Django 4.0.8 on 2024-11-27 05:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_essayquestion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='pass_mark',
            field=models.SmallIntegerField(default=50, help_text='Porcentaje necesario para aprobar el examen.', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Pass Mark'),
        ),
    ]
