# Generated by Django 4.2 on 2025-01-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0005_alter_quiz_pass_mark"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitting",
            name="fecha_aprobacion",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de Aprobación"
            ),
        ),
    ]
