# Generated by Django 4.2 on 2025-01-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0006_sitting_fecha_aprobacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitting",
            name="certificate_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
