# Generated by Django 4.2 on 2025-12-05 21:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0007_sitting_certificate_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quiz",
            options={
                "verbose_name": "Cuestionario",
                "verbose_name_plural": "Cuestionarios",
            },
        ),
        migrations.AlterField(
            model_name="mcquestion",
            name="choice_order",
            field=models.CharField(
                blank=True,
                choices=[
                    ("content", "Contenido"),
                    ("random", "Aleatorio"),
                    ("none", "Ninguno"),
                ],
                help_text="The order in which multiple-choice options are displayed to the user",
                max_length=30,
                verbose_name="Choice Order",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="answers_at_end",
            field=models.BooleanField(
                default=False,
                help_text="La respuesta correcta NO se muestra después de cada pregunta. Las respuestas se muestran al final.",
                verbose_name="Respuestas al final",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("assignment", "Tarea"),
                    ("exam", "Examen"),
                    ("practice", "Práctica"),
                ],
                help_text="Selecciona la categoría del cuestionario",
                max_length=20,
                verbose_name="Categoría",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Una descripción detallada del cuestionario",
                verbose_name="Descripción",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="description_en",
            field=models.TextField(
                blank=True,
                help_text="Una descripción detallada del cuestionario",
                null=True,
                verbose_name="Descripción",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="description_es",
            field=models.TextField(
                blank=True,
                help_text="Una descripción detallada del cuestionario",
                null=True,
                verbose_name="Descripción",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="description_fr",
            field=models.TextField(
                blank=True,
                help_text="Una descripción detallada del cuestionario",
                null=True,
                verbose_name="Descripción",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="description_ru",
            field=models.TextField(
                blank=True,
                help_text="Una descripción detallada del cuestionario",
                null=True,
                verbose_name="Descripción",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="draft",
            field=models.BooleanField(
                default=False,
                help_text="Si se marca, el cuestionario no se mostrará en la lista y solo puede ser tomado por usuarios que pueden editar cuestionarios.",
                verbose_name="Borrador",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="exam_paper",
            field=models.BooleanField(
                default=False,
                help_text="Si se marca, el resultado de cada intento por un usuario será almacenado. Necesario para calificación.",
                verbose_name="Examen evaluado",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="pass_mark",
            field=models.SmallIntegerField(
                default=50,
                help_text="Porcentaje necesario para aprobar el examen.",
                validators=[django.core.validators.MaxValueValidator(100)],
                verbose_name="Nota de aprobación",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="random_order",
            field=models.BooleanField(
                default=False,
                help_text="¿Mostrar las preguntas en orden aleatorio o como están configuradas?",
                verbose_name="Orden aleatorio",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="single_attempt",
            field=models.BooleanField(
                default=False,
                help_text="Si se marca, solo se permitirá un intento por usuario.",
                verbose_name="Un solo intento",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="title",
            field=models.CharField(max_length=500, verbose_name="Título"),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="title_en",
            field=models.CharField(max_length=500, null=True, verbose_name="Título"),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="title_es",
            field=models.CharField(max_length=500, null=True, verbose_name="Título"),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="title_fr",
            field=models.CharField(max_length=500, null=True, verbose_name="Título"),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="title_ru",
            field=models.CharField(max_length=500, null=True, verbose_name="Título"),
        ),
    ]
