# Generated by Django 4.2 on 2025-01-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="level",
        ),
        migrations.AddField(
            model_name="student",
            name="cargo",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="empresa",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
