# Generated by Django 4.2 on 2025-01-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_student_level_student_cargo_student_empresa"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="cargo",
        ),
        migrations.RemoveField(
            model_name="student",
            name="empresa",
        ),
        migrations.AddField(
            model_name="student",
            name="level",
            field=models.CharField(
                choices=[("Bachelor", "Bachelor Degree"), ("Master", "Master Degree")],
                max_length=25,
                null=True,
            ),
        ),
    ]
