# Generated by Django 4.2 on 2025-01-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_student_cargo_remove_student_empresa_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="cargo",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="empresa",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
