# Generated by Django 5.2.3 on 2025-07-04 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_student_cargo_student_empresa"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="picture",
        ),
    ]
